### ISSUE TITLE
Some discussion

### ISSUE THREAD

**Issue by mfeuerle** [frougon/xcref#1]
... to continue the discussion at [stackexchange](https://tex.stackexchange.com/a/505835)
I dont really get your question. Of corse the `noun` will change with respect to the case, 
Nominativ | der Abschnitt
Genitiv      | des Abschnitts / Abschnittes
Dativ         | dem Abschnitt
Akkusativ  | den Abschnitt
so it is not invariable with respect to the case. But this is so obvious, that i dont think that this was youre question...

**Comment by frougon** [comment]
I was thinking of the particular situation where no article is used (form = `prep+noun`). I was unsure whether the whole could depend on the case, because I was only thinking about genitive and couldn't find a meaningful example; but I think I have one now, with plural dative: one could say “in Abschnitten 3 und 4”, right? If so, this means the code has to know which case is used (nom/acc/dat/gen) even if the form is `prep+noun`—which is what I wanted to know.
